### ISSUE TITLE
Comments break test generation

### ISSUE THREAD

**Issue by ohanhi** [stoeffel/elm-doc-test#18]
I just started using elm-doc-test and it feels wonderful! :heart_eyes: 

I tried to explain the test cases with inline comments, and found that this case isn't really covered.

Input:
```elm
    -- when pressing no arrows
    >>> arrows []
    { x = 0, y = 0 }

    -- when pressing the left arrow
    >>> arrows [ ArrowLeft ]
    { x = -1, y = 0 }
```

Output (excerpt):
```elm
            \() ->
                (arrows [])
                |> Expect.equal ({ x = 0, y = 0 } -- when pressing the left arrow),
```

Prepending the single line comment with `>>>` resolves the issue, but this still means we can't do things like the following:

Input:
```elm
    >>> arrows [] -- no arrows
    { x = 0, y = 0 }
```
Output:
```elm
            \() ->
                (arrows [] -- no arrows)
                |> Expect.equal ({ x = 0, y = 0 }),
```

**Comment by stoeffel** [comment]
> I just started using elm-doc-test and it feels wonderful! 😍

❤️ glad you like it. Sorry for the late answer, I was on paternity leave.

I think there is an easy fix for this, will fix it as soon as I got time. A PR would be really welcome though 😄

**Comment by ohanhi** [comment]
No problem at all! 
I might have some time tonight or this weekend to make a PR. :) (I like that people put up issues before making PRs.)

**Comment by stoeffel** [comment]
> I might have some time tonight or this weekend to make a PR. :)

That would be awesome!

> I like that people put up issues before making PRs.

Totally.

Also, we can discuss doc-tests more in person at elm-europe, if you're going as well.

**Comment by ohanhi** [comment]
I am :+1:

**Comment by ohanhi** [comment]
@stoeffel Is it okay if I use `elm-format@exp` for the formatting? It adds some blank lines to the comment blocks, shifts `in` block contents and orders imports alphabetically.

**Comment by stoeffel** [comment]
yes, please. just switched as well.
