### ISSUE TITLE
fuzz doc tests

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/elm-doc-test#2]

**Comment by stoeffel** [comment]
_brain dump_
# inferring generators from type signature.

We want to keep the syntax for writing doc-test concise and easy to understand.

I suggest adding a new prefix to indicate fuzz tests f.e. `~~~`.
We need a way to reference an argument in the test. One way would be with vars like `_1`,`_2`...
or with a callback.

### Option 1
```elm
{-|
    ~~~ add _1 _2
    === toString _1 ++ _2
-}
add : Int -> String -> String
```

### Option 2
```elm
{-|
    ~~~ (a, b) -> add a b
    === (a, b) -> toString a ++ b
-}
add : Int -> String -> String
```

### Option 3
_I think I tend towards this option._
```elm
{-|
    ~~~ (a, b)
    >>> add a b
    === toString a ++ b
-}
add : Int -> String -> String
```

## Non-Default generators

An other problem is user defined types.
elm-doc-test.json would need to contain information about the generators.
```elm
{-| 
    ~~~ (user)
    >>> show user
    === user.firstName ++ " " ++ user.lastName
-}
show : User -> String
```

```json
{
  "root": "../",
  "tests": [
    "Mock",
    "Mock.Foo.Bar.Moo"
  ],
  "generators": {
    "User": "Gen.User"
  }
}
```

`Gen.User` would be in `tests/Gen/User.elm`

cc @eeue56 any ideas?

**Comment by eeue56** [comment]
@stoeffel Sorry, to expand what I meant by fuzz generators:

- the benefit of doc tests come from clearly explaining to the developer what the function does given particular inputs
- So generators in doctests should probably be discouraged
- but we can encourage a way of providing examples for a given function, e.g 

```
elm-doc-test --suggest Some.Module someFunction

someFunction : Int -> Int -> Int
> Given 0 and 0, what should someFunction return?
0

> Given 0 and 1, what should someFunction return?
1

```

etc, and then add these to the examples

**Comment by stoeffel** [comment]
yeah you're right. didn't think of it this way around. makes a lot more
sense 😄

On Sun, Nov 20, 2016, 21:50 Noah <notifications@github.com> wrote:

@stoeffel <https://github.com/stoeffel> Sorry, to expand what I meant by
fuzz generators:

   - the benefit of doc tests come from clearly explaining to the developer
   what the function does given particular inputs
   - So generators in doctests should probably be discouraged
   - but we can encourage a way of providing examples for a given function,
   e.g

elm-doc-test --suggest Some.Module someFunction

someFunction : Int -> Int -> Int
> Given 0 and 0, what should someFunction return?
0

> Given 0 and 1, what should someFunction return?
1


etc, and then add these to the examples

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/stoeffel/elm-doc-test/issues/2#issuecomment-261804622>,
or mute the thread

**Comment by lovasoa** [comment]
I think that
 
```elm
{-|
    ~~~ (a, b)
    >>> add a b
    === toString a ++ b
-}
add : Int -> String -> String
```

is quite a cryptic think to have in a documentation.

I think that users that don't know elm-doc test would be confused by the following line:
```
    ~~~ (a, b)
```

maybe 

```elm
{-|
    for all (a, b)
    >>> add a b
    === toString a ++ b
-}
add : Int -> String -> String
```
would be more understandable...

**Comment by jwoudenberg** [comment]
I wonder if it's more readable to explicitly define the type of the variables you want to fuzz. I think ideally, a syntax like this would be really nice:

```elm
{-|
    ~~~ for all a : Int, b : String
    >>> repeat a b |> length
    a * (length b)
    repeat : Int -> String
-}
```

It would of course be hard (but not necessarily impossible) to create fuzzers for arbitrary types. I guess one would potentially need to parse all the types in the project and it's dependencies to figure that out. So implementation wise, it might be easier to use existing fuzzer constructors, something like:

```elm
{-|
    ~~~ for all a <= int, b <= string
    >>> repeat a b |> length
    a * (length b)
    repeat : Int -> String
-}
```

**Comment by lovasoa** [comment]
Yes it would definetly be nice.

But it shouldn't replace custom generators completely, because it would be nice to be able to write
```elm
{-|
    ~~~ for all a <= PrimeNumber
    >>> isPrime a
    True
-}
isPrime : Int -> Bool
```
where we would define a custom generator called `PrimeNumber`

**Comment by stoeffel** [comment]
@jwoudenberg @lovasoa I like your proposal.
I think it wouldn't be hard to use it with custom fuzzers. You just import them as you would do for other doc-test-dependencies.

```elm
{-| imports for doc-tests
    >>> import MyFuzzer exposing (fuzzA, fuzzB)
-}
{-|
    ~~~ for all a <= fuzzA, b <= fuzzB
    >>> foo a b
    b.number * a.length
-}
repeat : Int -> String
```

**Comment by stoeffel** [comment]
@st56 we talked about this a few weeks ago. don't remember the discussion though. So pinging you hardy maybe you remember 😄

**Comment by stoeffel** [comment]
This is probably a bad idea. The reason why I think this is bad, is because it doesn't help writing good docs. maybe the suggestion thing that Noah proposed would be nice, could be it's own tool though.
